### ISSUE TITLE
Error while starting client

### ISSUE THREAD

**Issue by liaic** [superblaubeere27/IRC#1]
javax.net.ssl.SSLException: Unsupported record version Unknown-0.0
Disconnected
	at sun.security.ssl.InputRecord.checkRecordVersion(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:630)
	at java.lang.Thread.run(Unknown Source)
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)

**Comment by EpicCatto** [comment]
yes i have this problem 2

**Comment by DivineEnergylol** [comment]
its bc SSL shit and idk how fix so just copy the [examples](https://github.com/TooTallNate/Java-WebSocket/tree/master/src/main/example) from the [library's repo](https://github.com/TooTallNate/Java-WebSocket)
